# Generated by Django 5.0.7 on 2024-07-30 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_product_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='department',
        ),
        migrations.AddField(
            model_name='product',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.department'),
        ),
    ]
